/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 time_machine.glb 
*/

import { useGLTF } from '@react-three/drei';

export function TimeMachine(props) {
  const { nodes, materials } = useGLTF('3dModel/time_machine.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials['Material.021']}
        position={[-0.64, 1.695, 0.166]}
        rotation={[0.295, -0.017, -0.329]}
        scale={[0.758, 0.47, 0.907]}
      />
      <mesh
        geometry={nodes.Cube014.geometry}
        material={nodes.Cube014.material}
        position={[-0.089, 1.561, 0]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.009, 0.01, 0.003]}
      />
      <mesh
        geometry={nodes.Cube017.geometry}
        material={nodes.Cube017.material}
        position={[-0.005, 1.561, -0.091]}
        rotation={[1.097, 1.525, 0.45]}
        scale={[0.009, 0.011, 0.003]}
      />
      <mesh
        geometry={nodes.Cube021.geometry}
        material={nodes.Cube021.material}
        position={[-0.078, 1.561, -0.047]}
        rotation={[-0.049, -0.485, 1.537]}
        scale={[0.009, 0.01, 0.003]}
      />
      <mesh
        geometry={nodes.Cube022.geometry}
        material={nodes.Cube022.material}
        position={[-0.045, 1.561, -0.077]}
        rotation={[-0.095, -1.118, 1.46]}
        scale={[0.009, 0.011, 0.003]}
      />
      <mesh
        geometry={nodes.Cube027.geometry}
        material={nodes.Cube027.material}
        position={[0.033, 1.561, -0.083]}
        rotation={[0.088, 0.984, 1.472]}
        scale={[0.009, 0.011, 0.003]}
      />
      <mesh
        geometry={nodes.Cube030.geometry}
        material={materials['Material.030']}
        position={[-0.018, 1.401, 0.034]}
        rotation={[0, -1.563, 0]}
        scale={[0.022, 0.028, 0.022]}
      />
      <mesh
        geometry={nodes.Cube031.geometry}
        material={materials['Material.030']}
        position={[-0.049, 1.402, 0.005]}
        rotation={[Math.PI, -0.122, Math.PI]}
        scale={[0.022, 0.028, 0.022]}
      />
      <mesh
        geometry={nodes.Cube106.geometry}
        material={materials['Material.204']}
        position={[-0.64, 1.695, 0.166]}
        rotation={[0.295, -0.017, -0.329]}
        scale={[0.758, 0.47, 0.907]}
      />
      <mesh
        geometry={nodes.Cube107.geometry}
        material={nodes.Cube107.material}
        position={[-0.089, 1.561, 0]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.009, 0.01, 0.003]}
      />
      <mesh
        geometry={nodes.Cube108.geometry}
        material={nodes.Cube108.material}
        position={[-0.005, 1.561, -0.091]}
        rotation={[1.097, 1.525, 0.45]}
        scale={[0.009, 0.011, 0.003]}
      />
      <mesh
        geometry={nodes.Cube109.geometry}
        material={nodes.Cube109.material}
        position={[-0.078, 1.561, -0.047]}
        rotation={[-0.049, -0.485, 1.537]}
        scale={[0.009, 0.01, 0.003]}
      />
      <mesh
        geometry={nodes.Cube110.geometry}
        material={nodes.Cube110.material}
        position={[-0.045, 1.561, -0.077]}
        rotation={[-0.095, -1.118, 1.46]}
        scale={[0.009, 0.011, 0.003]}
      />
      <mesh
        geometry={nodes.Cube111.geometry}
        material={nodes.Cube111.material}
        position={[0.033, 1.561, -0.083]}
        rotation={[0.088, 0.984, 1.472]}
        scale={[0.009, 0.011, 0.003]}
      />
      <mesh
        geometry={nodes.Cube112.geometry}
        material={materials['Material.207']}
        position={[-0.018, 1.401, 0.034]}
        rotation={[0, -1.563, 0]}
        scale={[0.022, 0.028, 0.022]}
      />
      <mesh
        geometry={nodes.Cube113.geometry}
        material={materials['Material.207']}
        position={[-0.049, 1.402, 0.005]}
        rotation={[Math.PI, -0.122, Math.PI]}
        scale={[0.022, 0.028, 0.022]}
      />
      <mesh
        geometry={nodes.Sphere056.geometry}
        material={materials['Material.388']}
        position={[-0.207, 5.765, -10.183]}
        rotation={[-0.027, -0.337, -1.161]}
        scale={-0.004}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials['Material.003']}
        position={[1.741, 2.64, -0.123]}
        rotation={[0, 0.121, 0]}
        scale={[3.01, 0.32, 3.993]}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials['Material.004']}
        position={[2.001, 3.979, 1.581]}
        rotation={[0, 0.121, 0]}
        scale={[1.447, 1, 1]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials['Material.005']}
        position={[2.162, 3.801, 2.734]}
        rotation={[0.915, 0.074, -0.096]}
        scale={[0.65, 0.65, 0.079]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials['Material.011']}
        position={[2.181, 3.555, 2.893]}
        rotation={[0.915, 0.074, -0.096]}
        scale={[0.65, 0.65, 0.079]}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={materials['Material.012']}
        position={[2.206, 3.332, 3.078]}
        rotation={[0.915, 0.074, -0.096]}
        scale={[0.65, 0.65, 0.079]}
      />
      <mesh
        geometry={nodes.Cube024.geometry}
        material={materials['Material.013']}
        position={[2.261, 4.414, 1.261]}
        rotation={[0, 0.121, 0]}
        scale={[0.553, 0.139, 0.458]}
      />
      <mesh
        geometry={nodes.Sphere133.geometry}
        material={materials['Material.024']}
        position={[3.813, 3.233, -1.037]}
        rotation={[-1.56, 0.001, 0.121]}
        scale={[0.487, 0.831, 0.487]}
      />
      <mesh
        geometry={nodes.Sphere132.geometry}
        material={materials['Material.027']}
        position={[-0.417, 3.233, -0.522]}
        rotation={[-1.56, 0.001, 0.121]}
        scale={[0.487, 0.831, 0.487]}
      />
      <mesh
        geometry={nodes.Cube025.geometry}
        material={materials['Material.047']}
        position={[1.77, 3.302, -0.842]}
        rotation={[0, -1.437, 0]}
        scale={[0.959, 0.639, 1.298]}
      />
      <mesh
        geometry={nodes.Cylinder014.geometry}
        material={materials['Material.329']}
        position={[1.385, 4.359, 1.76]}
        rotation={[-0.526, 0.105, 0.061]}
        scale={[0.141, 0.952, 0.141]}
      />
      <mesh
        geometry={nodes.Sphere134.geometry}
        material={materials['Material.052']}
        position={[1.308, 5.331, 1.185]}
        rotation={[-0.526, 0.105, 0.061]}
        scale={[-0.295, -0.295, -0.259]}
      />
      <mesh
        geometry={nodes.Cylinder015.geometry}
        material={materials['Material.054']}
        position={[2.953, 3.888, -3.562]}
        rotation={[-0.123, 0.404, 0.533]}
        scale={[0.078, 0.45, 0.082]}
      />
      <mesh
        geometry={nodes.Sphere135.geometry}
        material={materials['Material.055']}
        position={[2.752, 4.32, -3.523]}
        rotation={[-0.123, 0.404, 0.533]}
        scale={[-0.164, -0.14, -0.151]}
      />
      <mesh
        geometry={nodes.Cube028.geometry}
        material={materials['Material.046']}
        position={[3.198, 3.535, -3.163]}
        rotation={[0, 0.121, 0]}
        scale={[0.611, 0.687, 0.812]}
      />
      <mesh
        geometry={nodes.Cylinder016.geometry}
        material={materials['Material.057']}
        position={[3.003, 3.888, -3.152]}
        rotation={[-0.123, 0.404, 0.533]}
        scale={[0.078, 0.45, 0.082]}
      />
      <mesh
        geometry={nodes.Sphere136.geometry}
        material={materials['Material.056']}
        position={[2.802, 4.32, -3.113]}
        rotation={[-0.123, 0.404, 0.533]}
        scale={[-0.164, -0.14, -0.151]}
      />
      <mesh
        geometry={nodes.Cylinder017.geometry}
        material={materials['Material.061']}
        position={[3.154, 3.868, -2.765]}
        rotation={[-0.033, 0.427, 0.225]}
        scale={[0.078, 0.45, 0.082]}
      />
      <mesh
        geometry={nodes.Sphere137.geometry}
        material={materials['Material.060']}
        position={[3.081, 4.34, -2.741]}
        rotation={[-0.033, 0.427, 0.225]}
        scale={[-0.164, -0.14, -0.151]}
      />
      <mesh
        geometry={nodes.BezierCurve014.geometry}
        material={materials['Material.004']}
        position={[-0.343, 3.653, 1.251]}
        rotation={[0.146, 1.403, 1.353]}
        scale={0.606}
      />
      <group
        position={[1.391, 8.549, 1.123]}
        rotation={[-0.52, -0.053, 0.083]}
        scale={[-0.758, -0.372, -0.444]}
      >
        <mesh
          geometry={nodes.Sphere117.geometry}
          material={materials['Material.004']}
        />
        <mesh
          geometry={nodes.Sphere117_1.geometry}
          material={materials['Material.068']}
        />
      </group>
    </group>
  );
}

useGLTF.preload('3dModel/time_machine.glb');
